### ISSUE TITLE
Freezing when asking too many questions in a row

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#102]
### Describe the solution you'd like

When I ask too many questions in a row, after a while it stops responding. Opening a new conversation solves the problem

**Comment by Eikosa** [comment]
I think I found the error code, but I'm not sure if this is it:
```
2023-08-30 13:54:07,622 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-216' coro=<BingAI.run() done, defined at /root/EdgeGPT-Telegram-Bot/src/backend.py:238> exception=KeyError('adaptiveCards')>
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/backend.py", line 260, in run
    async for final, resp in ut.CONV["all"][self.cid][self.conv_id][
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/EdgeGPT.py", line 187, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/chathub.py", line 178, in ask_stream
    resp_txt = result_text + response["arguments"][0][
KeyError: 'adaptiveCards'
```

**Comment by scmanjarrez** [comment]
Hmm, can you run the `/history_update` command, waiting few seconds and trying again? Sometimes, the history gets corrupted (the chat exists locally, but not on the server)

**Comment by Eikosa** [comment]
When I use this command, it does indeed solve the problem, but it is a bit annoying to do this every time it freezes and rewrite all my queries

**Comment by scmanjarrez** [comment]
Have you encountered this error again? I need more context to debug this error properly
