### ISSUE TITLE
The bot won't open: TypeError: Timeout.__init__() got an unexpected keyword argument 'connect'

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#111]
### The problem

The bot won't open:
```python3
root@ubuntu-s-4vcpu-8gb-intel-fra1-01:~/EdgeGPT-Telegram-Bot# sudo python3 src/edge.py 
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/edge.py", line 321, in <module>
    .build()
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_applicationbuilder.py", line 289, in build
    bot: Bot = self._build_ext_bot()  # build a bot
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_applicationbuilder.py", line 259, in _build_ext_bot
    request=self._build_request(get_updates=False),
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_applicationbuilder.py", line 240, in _build_request
    return HTTPXRequest(
  File "/usr/local/lib/python3.10/dist-packages/telegram/request/_httpxrequest.py", line 107, in __init__
    timeout = httpx.Timeout(
TypeError: Timeout.__init__() got an unexpected keyword argument 'connect'
```

### Version of python

 Python 3.10.12

### Version of EdgeGPT-Telegram-Bot

edge-gpt-telegram-bot v3.7.1 (legacy) (latest)

### Operating system running EdgeGPT-Telegram-Bot

Ubuntu 22.04.2 LTS

### Running on your machine? Running on docker?

.

### Logs & file uploads

.

**Comment by scmanjarrez** [comment]
Not happening in latest commit

**Comment by Eikosa** [comment]
Not fixed despite installing the latest version

**Comment by scmanjarrez** [comment]
Then it's not related to the bot. Check your dependencies, reinstall or upgrade them.

**Comment by Eikosa** [comment]
you are right! thank you very much, problem solved
