### ISSUE TITLE
/reset command not working

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#112]
### The problem

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_application.py", line 1173, in process_update
    await coroutine
  File "/usr/local/lib/python3.10/dist-packages/telegram/ext/_basehandler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/root/EdgeGPT-Telegram-Bot/src/cmds.py", line 253, in reset_bot
    os.execv(sys.argv[0], sys.argv)
PermissionError: [Errno 13] Permission denied
```

### Version of python

.

### Version of EdgeGPT-Telegram-Bot

.

### Operating system running EdgeGPT-Telegram-Bot

.

### Running on your machine? Running on docker?

.

### Logs & file uploads

.

**Comment by scmanjarrez** [comment]
you need to give execution permissions to src/edge.py
```
$ chmod +x src/edge.py
```

**Comment by scmanjarrez** [comment]
I'll keep it open until I add a try-except to explain this
