### ISSUE TITLE
"SSL error {error:0A000086:SSL routines::certificate verify failed}" when I used a verified certificate with a trusted root CA

### ISSUE THREAD

**Issue by kettly1260** [scmanjarrez/EdgeGPT-Telegram-Bot#28]
### The problem

1. When I used a verified certificate with a trusted root CA, the bot can not verified,  open "https://api.telegram.org/bot<token>/getWebhookinfo" showed that 
"ok":true,"result":{"url":"https://url/<bottoken>","has_custom_certificate":true,"pending_update_count":2,"last_error_date":1680013752,"last_error_message":"SSL error {error:0A000086:SSL routines::certificate verify failed}","max_connections":40,"ip_address":"VPS_ip"}}
This problem occurs regardless of whether I use nginx reverse proxy.
2. When I visit https://<url:port>/<token>:, the web page shows <html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>,the same error was showed on terminal : 

2023-03-28 14:45:20,844 - telegram.ext._utils.webhookhandler - DEBUG - 127.0.0.1 - Exception in TelegramHandler
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/tornado/web.py", line 1672, in _execute
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed

### Version of python

Python 3.10.9

### Version of EdgeGPT-Telegram-Bot

edge-gpt-telegram-bot v0.1.3

### Operating system running EdgeGPT-Telegram-Bot

Ubuntu 22.04

### Running on your machine? Running on docker?

machine

### Additional information & file uploads

2023-03-28 14:30:12,117 - hpack.hpack - DEBUG - Decoded 28, consumed 1 bytes
2023-03-28 14:30:12,117 - hpack.hpack - DEBUG - Decoded 2, consumed 1 bytes
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded (b'content-length', <memory at 0x7f03c6a64e80>), total consumed 4 bytes, indexed True
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded 17, consumed 1 bytes
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded 32, consumed 1 bytes
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded (b'strict-transport-security', b'max-age=31536000; includeSubDomains; preload'), total consumed 52 bytes, indexed False
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded 19, consumed 1 bytes
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded 1, consumed 1 bytes
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded (b'access-control-allow-origin', <memory at 0x7f03c6a64c40>), total consumed 23 bytes, indexed False
2023-03-28 14:30:12,118 - hpack.hpack - DEBUG - Decoded 20, consumed 1 bytes
2023-03-28 14:30:12,119 - hpack.hpack - DEBUG - Decoded 16, consumed 1 bytes
2023-03-28 14:30:12,119 - hpack.hpack - DEBUG - Decoded (b'access-control-allow-methods', b'GET, POST, OPTIONS'), total consumed 39 bytes, indexed False
2023-03-28 14:30:12,119 - hpack.hpack - DEBUG - Decoded 20, consumed 1 bytes
2023-03-28 14:30:12,119 - hpack.hpack - DEBUG - Decoded 37, consumed 1 bytes
2023-03-28 14:30:12,119 - hpack.hpack - DEBUG - Decoded (b'access-control-expose-headers', b'Content-Length,Content-Type,Date,Server,Connection'), total consumed 60 bytes, indexed False
2023-03-28 14:30:12,120 - httpx._client - DEBUG - HTTP Request: POST https://api.telegram.org/bot<token>/setWebhook "HTTP/2 200 OK"
2023-03-28 14:30:12,121 - telegram._bot - DEBUG - True
2023-03-28 14:30:12,121 - telegram._bot - DEBUG - Exiting: set_webhook
2023-03-28 14:30:12,130 - telegram.ext._utils.webhookhandler - DEBUG - Webhook Server started.
2023-03-28 14:30:12,130 - telegram.ext._updater - DEBUG - Waiting for webhook server to start
2023-03-28 14:30:12,130 - telegram.ext._updater - DEBUG - Webhook server started
2023-03-28 14:30:12,131 - apscheduler.scheduler - INFO - Scheduler started
2023-03-28 14:30:12,131 - telegram.ext._application - DEBUG - JobQueue started
2023-03-28 14:30:12,131 - telegram.ext._application - INFO - Application started
2023-03-28 14:30:12,131 - apscheduler.scheduler - DEBUG - Looking for jobs to run
2023-03-28 14:30:12,131 - apscheduler.scheduler - DEBUG - No jobs; waiting until a job is added

**Comment by scmanjarrez** [comment]
Are you filling the fields `ip` and `port` in your config.json? Your first error message seems to be using the word "vps_ip"

**Comment by scmanjarrez** [comment]
Are you using reverse proxy?

**Comment by kettly1260** [comment]
When using port 8443, no reverse proxy is used, and other ports are used

**Comment by scmanjarrez** [comment]
Have you checked the logs from your reverse proxy? Are your receiving POST requests from telegram?

**Comment by scmanjarrez** [comment]
Let's be clear, are you changing "myurl" by your real ip for privacy reasons, right? Does polling work for you? (Webhook: false)

**Comment by kettly1260** [comment]
Yes, to protect privacy.  And it works fine with polling

**Comment by scmanjarrez** [comment]
Do you have your server behind a router (local network) or a cloud service?

**Comment by kettly1260** [comment]
The port access is confirmed to be enabled, and the firewall has not blocked it. But there is no request from telegram. It should be due to certificate verify failed

**Comment by scmanjarrez** [comment]
That's really weird, telegram isn't supposed to verify certificate... you can even use self-signed certificates. Have you tested with a self-signed certificate?

**Comment by scmanjarrez** [comment]
Maybe you're not sending the full chain certificate? https://stackoverflow.com/questions/49308744/telegram-bot-ssl-error-ssl-error-error1416f086ssl-routinestls-process-serve

**Comment by kettly1260** [comment]
I have read the webpage, and at the same time read the difference between the self-signed certificate and the certified certificate on the url setting parameters on the tg official website. If you use the certified certificate, you don’t need to upload the certificate to the server, so I delete the certificate path in the config.json.  It can be used normally.
https://core.telegram.org/bots/webhooks

**Comment by scmanjarrez** [comment]
Ok. I'll add a condition for that case. Thanks

**Comment by kettly1260** [comment]
After using webhook for a period of time, I found that the reply is very slow when running in this mode, and some conversations will not be able to receive the reply normally, and the tg is always displayed in the sending process.  At the same time, the terminal has the following display
<details><summary>Details</summary>
<p>

ConnectionResetError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/ubuntu/docker/EdgeGPT-Telegram-Bot/src/cmds.py", line 293, in message
    await query.run()
  File "/home/ubuntu/docker/EdgeGPT-Telegram-Bot/src/utils.py", line 335, in run
    self._response = await CONV[self.cid].ask(
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/EdgeGPT.py", line 300, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/EdgeGPT.py", line 257, in ask_stream
    objects = str(await self.wss.recv()).split(DELIMITER)
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 568, in recv
    await self.ensure_open()
  File "/home/ubuntu/miniconda3/envs/edge/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 944, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

</p>
</details>

**Comment by scmanjarrez** [comment]
I don't think I can do anything about that, that looks like a problem with EdgeGPT. Sometime it crashed, but  I've not been able to reproduce the error consistently.
