### ISSUE TITLE
it suddenly stopped typing the message

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#82]
### The problem

![image](https://github.com/scmanjarrez/EdgeGPT-Telegram-Bot/assets/20538090/a55cd729-120e-4c7b-a8c2-7e704b6fd97a)

```bash
root@kelime:~/EdgeGPT-Telegram-Bot# sudo python3 src/edge.py 
2023-06-11 21:37:21,985 - apscheduler.scheduler - INFO - Scheduler started
2023-06-11 21:37:21,985 - telegram.ext._application - INFO - Application started
2023-06-11 21:37:27,197 - apscheduler.scheduler - INFO - Scheduler started
2023-06-11 21:37:27,197 - telegram.ext._application - INFO - Application started
2023-06-11 21:38:34,768 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-16' coro=<BingAI.run() done, defined at /root/EdgeGPT-Telegram-Bot/src/backend.py:70> exception=KeyError('adaptiveCards')>
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/backend.py", line 87, in run
    async for final, resp in ut.CONV["all"][self.cid][cur_conv][
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/EdgeGPT.py", line 155, in ask_stream
    async for response in self.chat_hub.ask_stream(
  File "/usr/local/lib/python3.10/dist-packages/EdgeGPT/chathub.py", line 156, in ask_stream
    resp_txt = result_text + response["arguments"][0][
KeyError: 'adaptiveCards'
```

### Version of python

3.10.7

### Version of EdgeGPT-Telegram-Bot

latest

### Operating system running EdgeGPT-Telegram-Bot

ubuntu

### Running on your machine? Running on docker?

.

**Comment by scmanjarrez** [comment]
Can you share the prompt?

**Comment by Eikosa** [comment]
`En fiyat performans robot süpürge`

**Comment by scmanjarrez** [comment]
Looks like an error in EdgeGPT, I'll test further.

**Comment by scmanjarrez** [comment]
By any chance were you running 3.1.0? I added a try except in 3.1.1 that should avoid this exception

**Comment by Eikosa** [comment]
Yes it was, sorry, I'm updating my code

**Comment by Eikosa** [comment]
Unfortunately the problem persists, here is another prompt: `polivagal teori nedir`

**Comment by scmanjarrez** [comment]
Oh, I think the problem is that I didn't update requiremens.txt because I could reproduce this bug in my server (running older version of EdgeGPT) but not in local, where I run the latest version

**Comment by Eikosa** [comment]
I think manual installation solved the problem, but not sure

**Comment by scmanjarrez** [comment]
Lets keep it open for the time being.
