### ISSUE TITLE
Can't start bot

### ISSUE THREAD

**Issue by Eikosa** [scmanjarrez/EdgeGPT-Telegram-Bot#88]
### The problem

```bash
root@kelime:~/EdgeGPT-Telegram-Bot# sudo python3 src/edge.py
Traceback (most recent call last):
  File "/root/EdgeGPT-Telegram-Bot/src/edge.py", line 308, in <module>
    ut.setup()
  File "/root/EdgeGPT-Telegram-Bot/src/utils.py", line 188, in setup
    if chats("history"):
  File "/root/EdgeGPT-Telegram-Bot/src/utils.py", line 222, in chats
    return DATA["config"]["chats"][key]
KeyError: 'history'
root@kelime:~/EdgeGPT-Telegram-Bot#
```

### Version of python

latest

### Version of EdgeGPT-Telegram-Bot

latest

### Operating system running EdgeGPT-Telegram-Bot

latest

### Running on your machine? Running on docker?

no

**Comment by scmanjarrez** [comment]
Check template, a new settings have been added:
```
remove_chats_on_stop: true/false delete/keep chats after bot stop/restart (⚠️ WARNING ⚠️: chats retrieved from Bing with /history_update will be deleted as well if you enable this feature).

history: true/false to enable/disable chat history.
```

**Comment by Eikosa** [comment]
thanks
